version: "3.4"

services:
  app:
    image: app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URL: ${MONGO_URI}
    ports:
      - 3000:3000
    depends_on:
      - mongo
    command: ["npm", "run", "dev"]
    volumes:
      - .:/usr/src/app
      # - node_modules:/usr/src/app/node_modules
    networks:
      - pg-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    # env_file:
    #   - .env
    networks:
      - pg-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: example
    depends_on:
      - mongo
    networks:
      - pg-network
  
  

networks:
  pg-network:
    driver: bridge

