### register new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Ismo",
    "email": "ismo@x.com",
    "password": "secret",
    "role": "customer"
   
}


### login user 7030052453, 8071172381
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "shab@x.com",
    "password": "secret"
    
}



### login user 7030052453, 8071172381
POST http://localhost:3000/api/auth/logout
Content-Type: application/json

{
    "phoneNumber": "1234567890",
    "password": "password1"
}


### create schedule
POST http://localhost:3000/api/merchants/schedules
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjU4MDU5ODkwOWE5ZDRjNjJlZmVmZmMiLCJpYXQiOjE3MTcwNDQ2MzJ9.-E1QhNo6On1x1iX6k9RsvUVNkAG0Qej2xay5oHy7NsU

{
   "scheduleDate": "2024-06-01",
  "startTime": "09:00",
  "endTime": "17:00"

}

### FETCH SChedules
GET  http://localhost:3000/api/merchants/schedules
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjU4MDU5ODkwOWE5ZDRjNjJlZmVmZmMiLCJpYXQiOjE3MTcwNDQ2MzJ9.-E1QhNo6On1x1iX6k9RsvUVNkAG0Qej2xay5oHy7NsU