### register new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "layo",
    "email": "layo@x.com",
    "password": "secret",
    "role": "merchant"
   
}


### login user 7030052453, 8071172381
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "layo@x.com",
    "password": "secret"
    
}



### login user 7030052453, 8071172381
POST http://localhost:3000/api/auth/logout
Content-Type: application/json

{
    "phoneNumber": "1234567890",
    "password": "password1"
}


### create schedule
POST http://localhost:3000/api/merchants/schedules
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjU4M2FjMTljYjcwNzJhYmQxNWVlMDciLCJpYXQiOjE3MTcwNTgyNDF9.DycK-XehzJL5YgdjYGaDzNK57gIMSdV5Pjtjb4B2OXg

{
   "scheduleDate": "2024-06-04",
  "startTime": "09:00",
  "endTime": "17:00"

}

### FETCH SChedules
GET  http://localhost:3000/api/merchants/schedules
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjU4M2FjMTljYjcwNzJhYmQxNWVlMDciLCJpYXQiOjE3MTcwNTgyNDF9.DycK-XehzJL5YgdjYGaDzNK57gIMSdV5Pjtjb4B2OXg


### FETCH appointments for mercnaht
GET  http://localhost:3000/api/merchants/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjU4M2FjMTljYjcwNzJhYmQxNWVlMDciLCJpYXQiOjE3MTcwNjQ0OTN9.kWkzXl5_zpLby4h41HyDN0ywjiDFHK4qNh81mK2vD1A

### cancel  appointment
PUT http://localhost:3000/api/merchants/appointments/cancel/665852671211b3fc98cb3bdc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjU4M2FjMTljYjcwNzJhYmQxNWVlMDciLCJpYXQiOjE3MTcwNjQ0OTN9.kWkzXl5_zpLby4h41HyDN0ywjiDFHK4qNh81mK2vD1A

{
 

}


### complete appointment
PUT http://localhost:3000/api/merchants/appointments/complete/66582055502ab6f1db7a8f5b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjU4MDU5ODkwOWE5ZDRjNjJlZmVmZmMiLCJpYXQiOjE3MTcwNDQ2MzJ9.-E1QhNo6On1x1iX6k9RsvUVNkAG0Qej2xay5oHy7NsU

{
  

}


### FETCH SChedules for merchant
GET  http://localhost:3000/api/customers/merchants
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjU4MDk1OTY3OTI2ZWExMTdmNmNhNzkiLCJpYXQiOjE3MTcwNTA1ODd9.e0u8su1CwruqqbyzOuNVvZPadcn1y932VxAsE_2rXdQ


### create appointment
POST http://localhost:3000/api/customers/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NjU4MDk1OTY3OTI2ZWExMTdmNmNhNzkiLCJpYXQiOjE3MTcwNTA1ODd9.e0u8su1CwruqqbyzOuNVvZPadcn1y932VxAsE_2rXdQ

{
    "merchantId": "66583ac19cb7072abd15ee07",
   "appointmentDate": "2024-06-04",
  "startTime": "10:00",
  "endTime": "11:00"

}